### ISSUE TITLE
Add more information to the readme file.

### ISSUE THREAD

**Issue by dingzw007** [MolSSI-SSS/QM_2017_SSS_Team7#31]
Maybe we could add in some background information about ourselves into the  README file

**Comment by kbsezginel** [comment]
Feel free to add information about yourself and make a pull request. We can all do the same thing.

**Comment by kbsezginel** [comment]
Make sure to pull from upstream first!
`git pull upstream master`

**Comment by SrinivasMushnoori** [comment]
We *could* do this but how does this help  the overall code?
I don't mind it, just want to point out that we could probably be working on updating the readme with more documentation on how to use the code, etc. because that's more useful. But again, yes, feel free to do so. I don't mind doing so myself.
